[RT-67] Add basic implementation
MLGMAG/rt-messenger pull request #2
Opened 2021-10-14 17:00 UTC by MLGMAG

2021-10-14 18:10 UTC, makrushinoff requested changes

2021-10-14 18:10 UTC, makrushinoff commented on src/main/java/com/webmuffins/rtsx/messenger/controller/MessageController.java
> +    @Resource
Remove this annotation

2021-10-14 18:10 UTC, makrushinoff commented on src/main/java/com/webmuffins/rtsx/messenger/converter/Converter.java
> +public interface Converter<SOURCE, TARGET> {
Use single letter

2021-10-14 18:10 UTC, makrushinoff commented on src/main/java/com/webmuffins/rtsx/messenger/converter/MessageResponseMessageConverter.java
> +        messageObj.setCreationDate(formattedCreationDate);
Use mapper style

2021-10-14 18:10 UTC, makrushinoff commented on src/main/resources/application.yaml
> +    pattern: 'dd/MM/yyyy HH:mm:ss.SSS'
use application.properties file

2021-10-15 10:20 UTC, MLGMAG commented on src/main/java/com/webmuffins/rtsx/messenger/converter/Converter.java
> +public interface Converter<SOURCE, TARGET> {
Done

2021-10-15 10:21 UTC, MLGMAG commented on src/main/java/com/webmuffins/rtsx/messenger/converter/MessageResponseMessageConverter.java
> +        messageObj.setCreationDate(formattedCreationDate);
Done

2021-10-15 10:21 UTC, MLGMAG commented on src/main/resources/application.yaml
> +    pattern: 'dd/MM/yyyy HH:mm:ss.SSS'
Done

2021-10-15 18:05 UTC, makrushinoff approved these changes

2021-10-16 10:20 UTC, merged